---
  - hosts: server
    remote_user: outscale
    become: yes
    vars:
      ansible_ssh_private_key_file: "~/.ssh/outscale_dev_bl.rsa"
      domain: 'redfish.blawesom.com'
    gather_facts: no
    roles:
      - redfish