###################
# Set users and hostname
###################
- name: Set hostname
  hostname: 
    name: "redfish"

###################
# Mist tools
###################
- name: Install repo
  package:
    name: https://centos7.iuscommunity.org/ius-release.rpm
    state: present

- name: Install prereq
  package :
    name: ['wget', 'curl', 'vim', 'git', 'htop']
    state: present

- name: Create log dir
  file:
    path: /var/log/redfish/
    state: directory

###################
# Security
###################
- name: Install fail2ban
  package:
    name: fail2ban
    state: present

- name: Start fail2ban service
  service: 
    name: fail2ban
    state: started
    enabled: true

- selinux:
    policy: targeted
    state: permissive

###################
# Front Web management
###################
- name: Install nginx, gunicorn
  package: 
    name: [nginx, python36u-gunicorn]
    state: latest

- name: Configure nginx
  copy:
    src: conf/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Start nginx service
  service:
    name: nginx
    state: started
    enabled: true


###################
# Python files and reqs
###################
- name: Creates directory
  file:
    path: /opt/redfish
    state: directory 

- name: Copy server files
  copy:
    src: "{{ item }}"
    dest: "/opt/redfish/"
  with_fileglob:
    - "./files/server/*"

- name: Install python
  package: 
    name: [python36u, python36u-pip]
    state: latest

- name: Install requirements
  pip:
    requirements: /opt/redfish/requirements.txt
    executable: pip3.6

- name: Add cronjob 
  cron:
    name: "SQL entry deletion"
    minute: 5
    job: "/usr/bin/python3.6 /opt/redfish/cron.py"

###################
# Supervisor
###################
- name: Install Supervisor
  package: 
    name: supervisor
    state: latest

- name: Conf Supervisor
  copy: 
    src: conf/supervisord.conf
    dest: /etc/

- name: Start supervisor service
  service: 
    name: supervisord 
    state: started
    enabled: true

- name: Copy conf for Supervirsord
  copy: 
    src: conf/server.conf
    dest: /etc/supervisord.d/
  notify:
  - restart supervisor
  - restart nginx
